cupicks/cupicks-be

- .gitignore
- package-lock.json
- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/app.ts
- src/middlewares/filters/_.exporter.ts
- src/middlewares/filters/content-type/application.json.filter.ts
- src/middlewares/filters/content-type/application.x.www.form.urlencoded.filter.ts
- src/models/_.loader.ts
- src/models/env/env.ts
- src/models/env/private/env.private.ts
- src/models/packets/i.user.packet.ts
- src/modules/providers/bcrypt.provider.ts
- src/modules/providers/jwt.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/routers/auth.router.ts
- src/routes/services/auth.service.ts
로그인 기능 구현이 완료되었습니다.
추가적으로 다음의 이슈에서 감지된 버그가 수정 되어 배포되었습니다.
- Issue #18 
- Issue #20
> PR : 로그인 기능 구현,  issue#18 #20

- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/routes/repositories/auth.repository.ts
- src/routes/services/auth.service.ts
금일 올라온 이슈 사항이 반영되었습니다.
- Issue #25
- Issue #26
> PR : 회원가입 및 로그인, 테이블 칼럼 길이 등 잔버그 수정 #25, #26

- src/app.ts
- src/middlewares/guards/_.exporter.ts
- src/middlewares/guards/cors/cors.guard.ts
- src/models/env/env.ts
- src/server.ts
> PR: cors middleware 생성

- src/models/_.loader.ts
- src/models/dtos/user/publish.token.dto.ts
- src/models/exceptions/custom.exception.ts
- src/models/packets/i.user.packet.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/routers/auth.router.ts
- src/routes/services/auth.service.ts
엑세스 토큰 재발행 구현이 완료되었습니다.
도메인 로직은 다음과 같습니다.
1. RefreshToken 이 누락된 경우
2. payload 안의 기준값을 가지고 찾은 유저가 없을 경우
1. user 테이블에 없을 경우
2. user_refresh 테이블에 없을 경우
3. db 안에 저장된 RefreshToken 이 없는 경우
1. 아직 1 회 이상 로그인 하지 않은 경우
2. 2 회 연속 로그인을 해서 첫 번째 RefreshToken 이 DB 에서 사라진 경우
_상황 예시 1. 여러 브라우저로 로그인 했을 시, 마지막 로그인 한 브라우저만 로그인 유지 가능_
> PR : 토큰 재발행 구현

- src/middlewares/filters/content-type/form.data.filter.ts
- src/modules/providers/multer.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/routers/auth.router.ts
아래 Bug 리포트를 해결한 것을 반영한 상태로 회원가입 로직에 업로드 기능을 추가하였습니다.
- Issue #20 
- Issue #34
> PR : 회원가입 로직에 업로드 기능 추가

- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/routers/auth.router.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/recipe.service.ts
PR : 유저 인증 미들웨어 추가 버전 완료 `src/routes/recipe`
> PR : 유저 인증 미들웨어 추가 버전 완료 `src/routes/recipe`

- src/models/_.loader.ts
- src/models/dtos/user/confirm.password.dto.ts
- src/models/dtos/user/publish.token.dto.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/routers/auth.router.ts
- src/routes/services/auth.service.ts
***joi.\*\*Schema*** 의 체이닝 메서드 사용 시, 문제가 발생하는 이슈가 식별되었고 해결하였습니다.
- Issue #46
> PR : 본인확인 도메인 구현 완료, #46

- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/recipe.service.ts
PR : 레시피 전체 조회 Reactor 예정 `src/routes`
> PR : 레시피 전체 조회 Reactor 예정 `src/routes`

- src/app.ts
- src/modules/providers/jwt.provider.ts
- src/modules/providers/multer.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/routers/_.exporter.ts
- src/routes/routers/auth.router.ts
- src/routes/routers/profile.router.ts
@unchaptered  @axisotherwise 
- Issue #51
> PR : 1주차 기술 피드백 - 코드리뷰 항목

- src/models/_.loader.ts
- src/models/dtos/user/edit.profile.dto.ts
- src/models/exceptions/custom.exception.ts
- src/routes/controllers/_.exporter.ts
- src/routes/controllers/profile.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/routers/profile.router.ts
- src/routes/services/_.exporter.ts
- src/routes/services/profile.service.ts
> PR : 회원 정보 수정 구현

- src/models/_.loader.ts
- src/models/dtos/user/edit.profile.dto.ts
- src/models/exceptions/custom.exception.ts
- src/routes/controllers/_.exporter.ts
- src/routes/controllers/profile.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/routers/profile.router.ts
- src/routes/services/_.exporter.ts
- src/routes/services/profile.service.ts
> PR : 유저 프로필 확인용 임의 도메인 추가

- src/modules/providers/jwt.provider.ts
- src/routes/services/auth.service.ts
아래 요구사항에 맞춰서 AccessToken 의 Payload 에 nickname 을 추가하였습니다.
- Issue #55
> PR : AccessToken Payload 에 nickname 추가, #55

- sql/dev.sql
- src/app.ts
- src/models/_.loader.ts
- src/models/dtos/comment/comment.dto.ts
- src/models/dtos/user/signup.user.dto.ts
- src/modules/providers/multer.provider.ts
- src/routes/controllers/_.exporter.ts
- src/routes/controllers/comment.controller.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/_.exporter.ts
- src/routes/repositories/comment.auth.repository.ts
- src/routes/routers/_.exporter.ts
- src/routes/routers/comment.router.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/_.exporter.ts
- src/routes/services/comment.service.ts
> PR : 댓글 작성 기능 구현 `src/`

- src/middlewares/multer.middleware.ts
- src/modules/providers/multer.provider.ts
- src/routes/controllers/comment.controller.ts
- src/routes/routers/comment.router.ts
PR : API 명세 수정사항 반영 `src`
- Issue #이슈번호
> PR : API 명세 수정사항 반영 `src`

- src/modules/providers/jwt.provider.ts
- src/routes/services/auth.service.ts
> PR : JwtProvider 확장 인터페이스 수정, #63

- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/modules/providers/jwt.provider.ts
- src/routes/repositories/auth.repository.ts
- src/routes/services/auth.service.ts
> PR : Simplify SQL user table, #66

- src/modules/providers/multer.provider.ts
- src/routes/controllers/comment.controller.ts
- src/routes/repositories/comment.auth.repository.ts
- src/routes/routers/comment.router.ts
- src/routes/services/comment.service.ts
PR : 주석 제거 `comment.controller.ts`
> PR : 주석 제거 `comment.controller.ts`

- src/routes/controllers/comment.controller.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/comment.auth.repository.ts
- src/routes/routers/comment.router.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/comment.service.ts
PR : Update 코멘트 삭제 시 s3 이미지 삭제 구현 `src/routers`
- Issue #61
> PR : Update 코멘트 삭제 시 s3 이미지 삭제 구현 `src/routers`

- src/routes/controllers/comment.controller.ts
- src/routes/repositories/comment.auth.repository.ts
- src/routes/routers/comment.router.ts
- src/routes/services/comment.service.ts
PR : 코멘트 업데이트 시 기존 s3 이미지 삭제 후 생성 구현 `src/routes`
- Issue #61
> PR : 코멘트 업데이트 시 기존 s3 이미지 삭제 후 생성 구현 `src/routes`

- src/constants/_.loader.ts
- src/constants/types/t.comment.response.ts
- src/models/dtos/comment/comment.dto.ts
- src/routes/controllers/comment.controller.ts
- src/routes/repositories/comment.auth.repository.ts
- src/routes/routers/comment.router.ts
- src/routes/services/comment.service.ts
PR : Create 레시피에 대한 코멘트 조회 기능 구현 `src/`
> PR : Create 레시피에 대한 코멘트 조회 기능 구현 `src/`

- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/comment.auth.repository.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/comment.service.ts
- src/routes/services/recipe.service.ts
> PR : 레시피 삭제 기능 구현 `src/`

- src/models/_.loader.ts
- src/models/dtos/recipe/update.recipe.dto.ts
- src/routes/controllers/comment.controller.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/comment.auth.repository.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/comment.service.ts
- src/routes/services/recipe.service.ts
PR : 레시피 업데이트 기능 구현 리팩토링 예정 `src/`
> PR : 레시피 업데이트 기능 구현 리팩토링 예정 `src/`

- lambda/index.js
- lambda/package-lock.json
- lambda/package.json
PR : 람다 이미지 리사이징 구현 `lambda/`
- Issue #78
> PR : 람다 이미지 리사이징 구현 `lambda/`

- src/models/dtos/recipe/update.recipe.dto.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/services/recipe.service.ts
PR : 레시피 업데이트 기능 구현 `recipe.controller.ts`
> PR : 레시피 업데이트 기능 구현 `recipe.controller.ts`

- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/models/dtos/user/confirm.email.dto.ts
- src/models/dtos/user/send.email.dto.ts
- src/models/dtos/user/signup.user.dto.ts
- src/models/dtos/user/singin.user.dto.ts
- src/models/packets/i.email.verify.packet.ts
- src/modules/_.loader.ts
- src/modules/providers/aws.ses.provider.ts
- src/modules/providers/date.provider.ts
- src/modules/providers/jwt.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.verify.list.repository.ts
- src/routes/services/auth.service.ts
다음의 이슈를 반영하여 구현이 완료되었습니다.
- Issue #68
특이사항으로는 다음의 내용이 있습니다.
> Update 반복 구문을 AwsSesProvider, DateProvider, JwtProvider 으로 추출
> 다음의 코드들을 Provider 함수 안에 추출하고 수정하였습니다.
> 
> - 현재 날씨를 mysql Datetime 에 맞게 추출해주는 코드 : DateProvider
> - 문자열 타입의 6자리 랜덤 숫자를 반환하는 코드 : AwsSesProvider
> - EmailVerifyToken, NicknameVerifyToken 에 대상자 email, nicknaem 등을 포함 : JwtProvider
>
> 출처 : https://github.com/cupicks/cupicks-be/commit/2a3db245243e5846b151fdd2d44134f8709e6625
> PR : 이메일 인증번호 확인 구현, #68

- src/models/dtos/user/confirm.nickname.dto.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/repositories/auth.verify.list.repository.ts
- src/routes/services/auth.service.ts
다음의 이슈를 반영하여 닉네임 중복확인 기능이 구현되었습니다.
- Issue #68
> PR : 닉네임 중복확인 구현, #68

- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/recipe.service.ts
> PR : 레시피 싫어요 기능 구현 `src/`

- src/constants/_.loader.ts
- src/constants/types/t.recipe.response.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/recipe.service.ts
PR : Create 레시피 상세 조회 구현 `src/`
> PR : Create 레시피 상세 조회 구현 `src/`

- package-lock.json
- package.json
- src/models/_.loader.ts
- src/models/dtos/user/logout.user.dto.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/routers/auth.router.ts
- src/routes/services/auth.service.ts
- tsconfig.json
09월 09일에 진행된 2차 기술 피드백에서 나왔던 별도의 ***로그아웃 도메인*** 이 완료되었습니다.
해당 도메인 실행 시, user 테이블의 ***refresh_token**** 값이 null 로 변경됩니다.
- Issue #108
> PR : 로그아웃 구현

- src/models/_.loader.ts
- src/models/dtos/user/send.password.dto.ts
- src/modules/_.loader.ts
- src/modules/generator/random.generator.ts
- src/modules/providers/aws.ses.provider.ts
- src/modules/providers/jwt.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/routers/auth.router.ts
- src/routes/services/auth.service.ts
- src/server.ts
- tsconfig.json
임시 비밀번호 발급이 구현되었습니다.
임시 비밀번호 발급은 ***RandomGenerator*** 라는 친구가 담당하고 있으며, 특수문자 ***!@#*** 2개 를 필수로 포함한 문자 + 숫자 12 자리 의 비밀번호를 만들어냅니다.
해당 도메인에서는 ***이메일, 임시 비밀번호*** 를 포함하고 있는 ***비밀번호 초기화 토큰*** 을 만들어서 사용자의 이메일로 전달합니다. 유효기간은 30분 입니다.
> PR : 임시 비밀번호 발급 구현

- src/modules/providers/aws.ses.provider.ts
- src/routes/services/auth.service.ts
***IResetPasswordToken*** 안의 payload 안에 ***기본 password*** 을 담아 놓고 있었습니다.
누락되어있는 단반향 암호화 구문을 추가하여 반영했습니다.
> PR : 임시 비밀번호 발송 도메인에 단방향 암호화 반영

- src/app.ts
- src/middlewares/guards/cors/cors.guard.ts
- src/models/_.loader.ts
- src/models/dtos/user/reset.password.dto.ts
- src/models/env/env.ts
- src/modules/providers/aws.ses.provider.ts
- src/modules/providers/jwt.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/routers/auth.router.ts
- src/routes/services/auth.service.ts
- src/server.ts
임시 비밀 번호 발급 및 승인 절차가 최종적으로 완성되었습니다.
- PR #110 
- PR #111 
해당 절차는 크게 2 단계로 진행이 됩니다.
1. 임시 비밀번호 발급 -> 임시 비밀번호 를 이메일로 발송 후, 2번 ***도메인 링크?resetPasswordToken=토큰*** 링크 생성
2. 임시 비밀번호 발급 승인 -> ***resetPasswordToken=토큰*** 을 이용해서 DB 에 접근해서 비밀번호를 변경, 이후 Frontend 의 ***signIn 페이지로 전달***
> PR : 발급된 임시 비밀번호 서버에 반영

- package-lock.json
- package.json
- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/models/packets/i.email.verify.packet.ts
- src/modules/_.loader.ts
- src/modules/providers/date.provider.ts
- src/modules/providers/dayjs.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.verify.list.repository.ts
- src/routes/services/auth.service.ts
다음의 이슈가 반영되어 수정되었습니다.
- Issue #116
- Issue #118
> PR : 사용자 이메일 발송횟수 제한, #116 #118

- src/models/env/env.ts
- src/models/packets/i.user.packet.ts
- src/modules/providers/aws.ses.provider.ts
- src/modules/providers/dayjs.provider.ts
- src/modules/providers/jwt.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/services/auth.service.ts
다음의 이슈를 반영하였고 추가적으로 누락된 조건문에 대한 처리를 완료했습니다.
- Issue #116
- Issue #118
> PR : 이메일 중복확인 메일 발송 제한 추가 수정, #116 #118

- src/routes/controllers/comment.controller.ts
- src/routes/services/comment.service.ts
- src/server.ts
- Issue #133 
이슈가 반영되었습니다.
1. 2개의 **Lambda** **Trigger** 가 추가되었습니다.
- profile/ 
```javascript
const s3Object = await s3.getObject({ Bucket, Key }).promise();
// 프로필 이미지 리사이징 옵션
const resizedImage = await sharp(s3Object.Body)
.resize(600, 600, { fit: "inside" })
.toFormat(format)
.toBuffer();
await s3.putObject(
{
Bucket,
Key: `profile-resized/${filename}`, // 저장 경로
Body: resizedImage,
}
).promise();
return done(null, `profile-resized/${filename}`);
```
- comment/
```javascript
const s3Object = await s3.getObject({ Bucket, Key }).promise();
// 코멘트 이미지 리사이징 옵션
const resizedImage = await sharp(s3Object.Body)
.resize(400, 400, { fit: "inside" })
.toFormat(format)
.toBuffer();
await s3.putObject(
{
Bucket,
Key: `comment-resized/${filename}`, // 저장 경로
Body: resizedImage,
}
).promise();
return …
```
> Update  이슈 반영에 따른 이미지 처리 로직 업데이트

- src/server.ts
- tsconfig.json
> 현재 점점 ***build*** 속도 저하가 발생하는 이슈가 어느 정도 해결이 되었습니다.
> 
> - Issue #108
> - Issue #128
> - Issue #137
종속성 확인을 한 후에 최종적으로 ***vite***  도입을 결정하면 될 것 같습니다.
> PR : tsc tuning

- src/modules/providers/aws.ses.provider.ts
- src/server.ts
- tsconfig.json
> cupick@1.3.4.1

- src/models/env/env.ts
> cupick@1.3.4.2

- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/models/dtos/request.query.extractor.ts
- src/models/dtos/user/edit.profile.dto.ts
- src/models/dtos/user/signup.user.dto.ts
- src/models/dtos/user/user.dto.ts
- src/modules/providers/multer.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/controllers/profile.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/routers/auth.router.ts
- src/routes/routers/profile.router.ts
- src/routes/services/auth.service.ts
- src/routes/services/profile.service.ts
다음의 이슈를 반영하였습니다.
- Issue #108 
- Issue #144
> PR : 회원가입 및 프로필 수정에 이미지 재업로드 구현, #108

- src/models/dtos/comment/create.comment.dto.ts
- src/models/dtos/comment/update.comment.dto.ts
- src/routes/controllers/comment.controller.ts
- src/routes/repositories/comment.repository.ts
- src/routes/services/comment.service.ts
PR : 변경사항 `./src/*`
다음 이슈가 반영되었습니다!
- Issue #144 
- Issue #133 
- Issue #107
> PR: 다음 이슈 반영 #144 #133 #107

- src/middlewares/guards/cors/cors.guard.ts
BugFix CORS allow options PATCH 메서드 오타 수정
> BugFix CORS allow options PATCH 메서드 오타 수정

- scripts/after-deploy.sh
> cupick@1.3.4.5

- src/routes/services/auth.service.ts
> HotFix 회원가입에 잘못된 조건문 분기 처리 수정

- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/recipe.repository.ts
> HotFix 레시피 상세 조회에 누락된 nickname, imageUrl, resizedUrl 전달

- package.json
- src/models/exceptions/custom.exception.ts
- test/_.fake.datas/fixture/exception.fixture.ts
- test/integration/env.system.test.ts
- test/integration/sample.test.ts
- test/unit/models/env/env.test.ts
- test/unit/models/exception/custom.exception.test.ts
- test/unit/routes/controllers/_.exporter.test.ts
- test/unit/routes/repositories/_.exporter.test.ts
- test/unit/routes/routers/_.exporter.test.ts
- test/unit/routes/services/_.exporter.test.ts
아래 PR 에서 구현한 테스트 자동화가 제대로 작동하는 지 확인 겸, 아주 간단한 `routes/*/_.exportet` 테스트 코드를 작성하였습니다.
- PR #156
> TEST : 기본적인 `~routes/*/_.exporter` 테스트 코드 작성

- src/modules/providers/multer.provider.ts
HotFix 사용자 프로필 이미지 **s3** 에 저장 안되는 에러 해결
> HotFix 사용자 프로필 이미지 **s3** 에 저장 안되는 에러 해결

- test/integration/sample.test.ts
- test/unit/models/env/env.test.ts
다음의 PR 에서 구현한 ***테스트 자동화*** 를 확인하기 위한 PR 입니다.
- PR #156
> TEST : Test 샘플 테스트 코드 추가

- src/models/dtos/recipe/create.recipe.dto.ts
- src/models/dtos/recipe/update.recipe.dto.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/routers/recipe.router.ts
- src/routes/services/recipe.service.ts
PR : 레시피/댓글 CRUD Dto 클래스의 constructor 매개 변수 리팩토링 `src./*`
> PR : 레시피/댓글 CRUD Dto 클래스의 constructor 매개 변수 리팩토링 `src./*`

- src/constants/_.loader.ts
- src/constants/error_list/error.list.ts
- src/middlewares/multer.middleware.ts
- src/models/exceptions/custom.exception.ts
- src/modules/providers/bcrypt.provider.ts
- src/modules/providers/jwt.provider.ts
- src/modules/providers/multer.provider.ts
- src/modules/providers/mysql.provider.ts
- src/modules/validators/joi.validator.ts
- src/routes/controllers/auth.controller.ts
- src/routes/controllers/comment.controller.ts
- src/routes/controllers/profile.controller.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/auth.repository.ts
- src/routes/repositories/auth.verify.list.repository.ts
- src/routes/repositories/comment.repository.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/services/auth.service.ts
- src/routes/services/comment.service.ts
- src/routes/services/profile.service.ts
- src/routes/services/recipe.service.ts
- test/unit/models/exception/custom.exception.test.ts
FE 에서 분기처리를 위한 값을 달라고 부탁하셔서, 전 도메인에 걸쳐서 `에러 발생 시점` 으로 분류되는 4XX ~ 5XX 상태코드일 때의 ERROR_CODE_LIST 를 만들었습니다.
> PR :유지보수를 위한 TERROR_CODE 추가

- src/constants/error_list/error.list.ts
- src/routes/services/comment.service.ts
- src/routes/services/recipe.service.ts
> cupick@1.3.4.7

- .github/workflows/auto.deploy.yml
- package-lock.json
- package.json
- src/constants/error_list/error.list.ts
- src/routes/services/comment.service.ts
- src/routes/services/recipe.service.ts
PR : UuidProvider 공급자 추가와 UuidProvider 를 활용한 s3 이미지 저장 로직 개선 `./src/*`
> cupick@1.3.4.9

- package.json
- tsconfig.build.json
- tsconfig.json
다음의 이슈가 반영되었습니다.
- Issue #137
- Issue #138
> PR : tsc, tsc-watch 를 `tsc` 로 통일

- package-lock.json
- package.json
- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/routes/services/profile.service.ts
- tsconfig.build.json
- tsconfig.json
@cmun2 이 발견하신 에러 수정했습니다.
`ProfileService.prototype.getMyRecipe` 안에서 내부에서 `getLikeRecipeByUserid` 가 호출되고 있어서 해당 메서드를 다음 `getMyRecipeByUserId` 으로 변경하였습니다.
> cupick@1.3.4.91

- package.json
다음 PR 이후에 식별된 Issue 를
- PR #182
- Issue #183
> cupick@1.3.4.92

- .github/workflows/auto.deploy.yml
다음 PR 이후에 식별된 Issue 를 반영했습니다.
- PR #182
- Issue #183
> cupick@1.3.4.93

- src/models/packets/i.recipe.packet.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/services/profile.service.ts
다음의 이슈가 반영되었습니다.
- Issue #164 
- Issue #186
> PR : 내 레시피, 좋아요 레시피 조회, #186

- .github/workflows/auto.jest.runner.yml
- sample.txt
> PR : Automated-Jest 의 node_modules cache, #166

- jest.config.json
- jest/jest.config.e2e.json
- jest/jest.config.int.json
- jest/jest.config.unit.json
- package-lock.json
- package.json
- test/unit/routes/controllers/_.exporter.test.ts
다음의 이슈를 반영하여 `ts-jest` 를 제거하고 `estbuild-jest` 를 설치했습니다.
- Issue #164 
- 튜닝 전 : 최초 실행 120초, 반복실행 55 초
- 튜닝 후 : 최초 실행 3 ~ 30 초 (대체적으로 3\~5초), 반복 실행 2 \~ 8 초 (대체적으로 2~3초)
실제로 VM ubuntu 의 결과로도 가시적인 차이가 발생하고 있습니다.
- 1 번의 경우 : 59초
- 2 번의 경우 : 15초
- 3 번의 경우 : 11초
> PR : `jest` tuning, #164

- src/routes/controllers/_.exporter.ts
- src/routes/controllers/auth.controller.ts
- src/routes/controllers/comment.controller.ts
- src/routes/controllers/profile.controller.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/routers/_.exporter.ts
- src/routes/routers/auth.router.ts
- src/routes/routers/comment.router.ts
- src/routes/routers/profile.router.ts
- src/routes/routers/recipe.router.ts
export defualt 로 내보내기 중인 파일을 모두 export 로 변경하였습니다.
예외가 되는 파일은 다음과 같습니다.
- `~/src/app.ts`
- `~/src/server.ts`
> PR : 일관성있는 mocking 을 위한 export defulat -> export 통일

- src/models/_.loader.ts
- src/models/dtos/profile/get.like.recipe.dto.ts
- src/models/dtos/profile/get.my.recipe.dto.ts
- src/modules/_.loader.ts
- src/modules/factory/dto.factory.ts
- src/routes/controllers/auth.controller.ts
- src/routes/controllers/comment.controller.ts
- src/routes/controllers/profile.controller.ts
- src/routes/controllers/recipe.controller.ts
> PR : 유지보수를 위한 DtoFactory 도입, #201

- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
sql/*.sql 의 손상된 INSERT INTO 구문을 수정하였습니다.
> PR : HotFix SQL Table Query 의 insert 구문 오타 수정

- sql/default.sql
- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/models/dtos/request.query.extractor.ts
- src/models/dtos/user/signup.user.dto.ts
- src/models/dtos/user/user.dto.ts
- src/models/enums/_.exporter.ts
- src/models/enums/e.recipe.category.ts
- src/modules/factory/dto.factory.ts
- src/routes/controllers/auth.controller.ts
- src/routes/repositories/_.exporter.ts
- src/routes/repositories/user.category.repository.ts
- src/routes/services/auth.service.ts
> PR : 회원가입에 선호 및 비선호 재료 선택 반영, #203

- src/models/dtos/profile/edit.profile.dto.ts
- src/modules/factory/dto.factory.ts
- src/routes/controllers/profile.controller.ts
- src/routes/repositories/user.category.repository.ts
- src/routes/services/profile.service.ts
> PR : 회원가입에 선호 및 비선호 재료 선택 반영

- src/routes/services/recipe.service.ts
현재 사용자가 좋아요를 누른 레시피인지 구분하기 위해 다음 사항이 추가되었습니다.
- GET api/recipes/:recipeId
레시피 상세 조회 응답 데이터로 **isLiked** 형식이 추가되었습니다.
```typescript
{
isSuccess: true,
message: '레시피 조회에성공하셨습니다.’,
recipe: {
recipeId: 123456,
title: ‘레시피 이름’,
content:  ‘레시피 본문',
isIced: boolean,
cupSize: 355 | 473 | 591,
createdAt: ‘2022-~~’,
updatedAt: ‘2022-~~,
isLiked: boolean,
ingredientList: [{
ingredientName: ‘음식 재료 이름’,
ingredientColor: ‘#123456’,
ingredientAmount: 100
}]
}
}
```
> cupick@1.3.55

- sql/dev.sql
- sql/prod.sql
- sql/test.sql
- src/app.ts
- src/models/_.loader.ts
- src/models/dtos/ranking/best.recipe.dto.ts
- src/models/dtos/recipe/create.recipe.dto.ts
- src/models/dtos/recipe/update.recipe.dto.ts
- src/models/packets/i.best.recipe.packet.ts
- src/models/packets/i.weekly.packet.ts
- src/modules/factory/dto.factory.ts
- src/modules/providers/dayjs.provider.ts
- src/modules/providers/multer.provider.ts
- src/routes/controllers/_.exporter.ts
- src/routes/controllers/ranking.controller.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/_.exporter.ts
- src/routes/repositories/ranking.repository.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/routers/_.exporter.ts
- src/routes/routers/ranking.router.ts
- src/routes/services/_.exporter.ts
- src/routes/services/ranking.service.ts
- src/routes/services/recipe.service.ts
- test/unit/routes/controllers/_.exporter.test.ts
- test/unit/routes/repositories/_.exporter.test.ts
- test/unit/routes/routers/_.exporter.test.ts
- test/unit/routes/services/_.exporter.test.ts
Reverts cupicks/cupicks-be#215
> Revert "Revert "PR : 주간 베스트 레시피 조회 기능""

- sql/prod.sql
- sql/test.sql
- src/models/_.loader.ts
- src/models/dtos/recipe/create.recipe.dto.ts
- src/models/dtos/recipe/update.recipe.dto.ts
- src/modules/factory/dto.factory.ts
(CreateRecipe|UpdateReceipe)Dto 의 category 를 선택값으로 변경
> cupick@1.3.62

- src/models/dtos/recipe/create.recipe.dto.ts
- src/models/dtos/recipe/update.recipe.dto.ts
> cupick@1.3.63

- src/models/_.loader.ts
- src/models/packets/i.recipe.owner.packet.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/services/profile.service.ts
> PR : 내가 좋아요한 레시피 버그 수정

- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/services/recipe.service.ts
> cupick@1.3.66

- package-lock.json
- package.json
> cupick@1.3.68

- appspec.yml
```cmd
Script does not exist at specified location: /opt/codedeploy-agent/deployment-root/a7c825dc-0b3d-4218-8b87-8c82516339e2/d-YEH8F0UZ6/deployment-archive/home/ubuntu/project/scripts/after-deploy.sh
```
> cupick@1.3.691

- src/constants/_.loader.ts
- src/constants/types/t.comment.response.ts
- src/models/_.loader.ts
- src/models/packets/i.best.recipe.category.packet.ts
- src/models/packets/i.best.recipe.packet.ts
- src/modules/factory/dto.factory.ts
- src/modules/providers/dayjs.provider.ts
- src/routes/controllers/comment.controller.ts
- src/routes/controllers/ranking.controller.ts
- src/routes/controllers/recipe.controller.ts
- src/routes/repositories/comment.repository.ts
- src/routes/repositories/ranking.repository.ts
- src/routes/services/comment.service.ts
- src/routes/services/ranking.service.ts
PR: Refactor 코드 컨벤션에 맞는 리팩토링 과 Controller 에서 직접 데이터 응답하는 로직 개선
- Issue #232
> PR: Refactor 코드 컨벤션에 맞는 `리팩토링` 과 `Controller` 에서 직접 데이터 응답하는 로직 개선

- src/routes/repositories/comment.repository.ts
- src/routes/services/comment.service.ts
**PUT /api/comments/:commentId?comment=""**
- 기존 응답 형식
```typescript
{
isSuccess: true,
message: '댓글 수정에 성공하였습니다.',
comment: {
userId: 1234,
nickname: '유저 닉네임',
recipeId: 1234,
commentId: 12354,
imageUrl: 'http://',
resizedUrl: ‘리사이징 URL’,
comment: '이것은 댓글입니다.',
createdAt: '2022-08~~' // Date 양식
updatedAt: '2022-08~~' // Date 양식
}
}
```
- 변경 응답 형식
```typescript
{
isSuccess: true,
message: '댓글 수정에 성공하였습니다.',
comment: {
userId: 1234,
nickname: '유저 닉네임',
userImageUrl: “http.//”,
userResizedUrl: “리사이징 URL”,
recipeId: 1234,
commentId: 12354,
imageUrl: 'http://',
resizedUrl: ‘리사이징 URL’,
comment: '이것은 댓글입니다.',
createdAt: '2022-08~~' // Date 양식
updatedAt: '2022-08~~' // Date 양식
}
}
```
> PR: Update 코멘트 업데이트 기능 응답 데이터 형식 수정

- .github/workflows/auto.deploy.yml
- .github/workflows/auto.jest.runner.yml
- appspec.yml
- content/nginx/cupick.ddns.net
- scripts/after-install.sh
- src/app.ts
- test.sh
> cupick@1.3.693 #248

- README.md
- src/modules/providers/jwt.provider.ts
- src/routes/services/auth.service.ts
- test/unit/routes/services/auth.service.test.ts
PR: RefreshToken 인터페이스와 테스트 케이스 수정
> PR: RefreshToken 인터페이스와 테스트 케이스 수정

- src/models/_.loader.ts
- src/models/packets/i.best.recipe.comment.packet.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/services/ranking.service.ts
- src/routes/services/recipe.service.ts
PR: 베스트 랭킹 레시피 조회에 댓글 갯수 응답 데이터 추가와 댓글 갯수 조회 쿼리에 올바른 Packet 타입 생성
> PR: 베스트 랭킹 레시피 조회에 댓글 갯수 응답 데이터 추가와 댓글 갯수 조회 쿼리에 올바른 Packet 타입 생성

- src/routes/repositories/recipe.repository.ts
- src/routes/services/recipe.service.ts
> PR: 레시피 상세 조회 쿼리와 응답 데이터 수정

- src/models/packets/i.best.recipe.comment.packet.ts
- src/models/packets/i.recipe.like.packet.ts
- src/routes/repositories/recipe.repository.ts
- src/routes/services/recipe.service.ts
PR: 레시피 전체 조회 좋아요 갯수 응답 쿼리 수정과 올바른 Packet 생성
> PR: 레시피 전체 조회 좋아요 갯수 응답 쿼리 수정과 올바른 Packet 생성

- src/models/dtos/comment/create.comment.dto.ts
- src/models/dtos/comment/update.comment.dto.ts
- src/modules/factory/dto.factory.ts
- src/routes/controllers/comment.controller.ts
- src/routes/repositories/ranking.repository.ts
- src/routes/services/ranking.service.ts
PR: 주간 베스트 레시피 조회 전 주 레시피도 같이 조회되는 에러 수정
> PR: 주간 베스트 레시피 조회 전 주 레시피도 같이 조회되는 에러 수정

- src/models/dtos/profile/edit.profile.dto.ts
- src/models/dtos/user/confirm.email.dto.ts
- src/models/dtos/user/confirm.nickname.dto.ts
- src/models/dtos/user/reset.password.dto.ts
- src/models/dtos/user/send.email.dto.ts
- src/models/dtos/user/send.password.dto.ts
- src/models/dtos/user/signup.user.dto.ts
- src/modules/factory/dto.factory.ts
- src/modules/providers/dayjs.provider.ts
- src/routes/controllers/auth.controller.ts
- src/routes/controllers/profile.controller.ts
- src/routes/routers/auth.router.ts
- test/_.fake.datas/fixture/models/dtos/user.dto.fixture.provider.ts
- test/_.fake.datas/fixture/user.dto.fixture.provider.ts
> PR : API 명세 수정에 의한 /auth 및 /profile 도메인 리팩토링

- src/routes/routers/auth.router.ts
비즈니스 로직에서 불필요하다고 판단된 미들웨어가 제거되었습니다.
> cupick@1.4.011

- src/routes/controllers/auth.controller.ts
- src/routes/services/auth.service.ts
- test/unit/routes/controllers/auth.controller.test.ts
- test/unit/routes/services/auth.service.test.ts
> PR : 비밀번호 변경 도메인 수정, #272

- src/models/dtos/profile/edit.profile.dto.ts
- src/models/dtos/user/signup.user.dto.ts
- src/modules/factory/dto.factory.ts
- src/routes/controllers/profile.controller.ts
- src/routes/repositories/_.exporter.ts
- src/routes/repositories/user.favor.repository.ts
- src/routes/services/auth.service.ts
- src/routes/services/profile.service.ts
- test/unit/routes/repositories/_.exporter.test.ts
기존에 DB 에는 유저가 ***선호/비선호하는 재료 카테고리*** 에 대해서만 기록이 되고 있었습니다.
이 부분에 대해서 유저가 ***선호/비선호하는 사이즈/온도/재료 카테고리*** 에 대해서 기록하고자 합니다.
세부적인 카테고리 사항은 다음의 협업 문서를 확인해주세요.
- https://www.notion.so/801c75580da74d7fb3e83c19d931f38b
추가적으로 다음과 같은 마이그레이션이 적용되었습니다.
- Issue #274
> PR : 프로필 수정 도메인에 선호 및 비선호 체계 적용

- src/routes/repositories/bedge.repository.ts
Query 에 누락된 변수를 추가하고 버그를 수정하였습니다.
> cupick@1.4.21
